
export enum  TdechargmentsActionType{
    GET_TDECHARGMENT_LIST="GET_TDECHARGMENT_LIST",
    GET_TDECHARGMENT_LISTV2="GET_TDECHARGMENT_LISTV2",
    GET_TDECHARGMENTS_CREATE="GET_TDECHARGMENTS_CREATE",
    PACTH_TDECHARGMENTS_UPDATE="PACTH_TDECHARGMENTS_UPDATE",
    GET_SEARCH_TDECHARGMENTS_LIST="GET_SEARCH_TDECHARGMENTS_LIST",
    DELETE_TDECHARGMENT="DELETE_TDECHARGMENT",
    PACTH_TDECHARGMENTS_UPDATE_STATUS="PACTH_TDECHARGMENTS_UPDATE_STATUS",
    GET_TDECHARGMENT_GETPHOTO="GET_TDECHARGMENT_GETPHOTO",
    GET_TDECHARGMENT_DETAIL="GET_TDECHARGMENT_DETAIL",
}

