
export enum  StacksActionType{
    GET_STACK_LIST="GET_STACK_LIST",
    GET_STACKS_CREATE="GET_STACKS_CREATE",
    PACTH_STACKS_UPDATE="PACTH_STACKS_UPDATE",
    GET_SEARCH_STACKS_LIST="GET_SEARCH_STACKS_LIST",
    DELETE_STACK="DELETE_STACK"

    
}

