
export enum  VehiclebrandsActionType{
    GET_VEHICLEBRAND_LIST="GET_VEHICLEBRAND_LIST",
    GET_VEHICLEBRANDS_CREATE="GET_VEHICLEBRANDS_CREATE",
    PACTH_VEHICLEBRANDS_UPDATE="PACTH_VEHICLEBRANDS_UPDATE",
    GET_SEARCH_VEHICLEBRANDS_LIST="GET_SEARCH_VEHICLEBRANDS_LIST",
    DELETE_VEHICLEBRAND="DELETE_VEHICLEBRAND",
    PACTH_VEHICLEBRANDS_UPDATE_STATUS="PACTH_VEHICLEBRANDS_UPDATE_STATUS",
    GET_VEHICLEBRANDS_GETSTATS="GET_VEHICLEBRANDS_GETSTATS",


}

