
export enum  SupmanagersActionType{
    GET_SUPMANAGER_LIST="GET_SUPMANAGER_LIST",
    GET_SUPMANAGERS_CREATE="GET_SUPMANAGERS_CREATE",
    PACTH_SUPMANAGERS_UPDATE="PACTH_SUPMANAGERS_UPDATE",
    GET_SEARCH_SUPMANAGERS_LIST="GET_SEARCH_SUPMANAGERS_LIST",
    DELETE_SUPMANAGER="DELETE_SUPMANAGER",
    PACTH_SUPMANAGERS_UPDATE_STATUS="PACTH_SUPMANAGERS_UPDATE_STATUS",
    GET_SUPMANAGERS_GETSTATS="GET_SUPMANAGERS_GETSTATS",


    //////////////SUPPLIERTOMANAGER SECTION ////////////
    GET_ALL_SUPPLIER_BY_SUPMANAGER_ID="GET_ALL_SUPPLIER_BY_SUPMANAGER_ID",
    AFFECT_ALL_MANAGER_TO_SUPLIER="AFFECT_ALL_MANAGER_TO_SUPLIER",
    DELETE_SUPPLIER_BY_SUPMANAGER_ID="DELETE_SUPPLIER_BY_SUPMANAGER_ID"
}

