
export enum  FtransfertsActionType{
    GET_FTRANSFERT_LIST="GET_FTRANSFERT_LIST",
    GET_FTRANSFERTS_CREATE="GET_FTRANSFERTS_CREATE",
    PACTH_FTRANSFERTS_UPDATE="PACTH_FTRANSFERTS_UPDATE",
    GET_SEARCH_FTRANSFERTS_LIST="GET_SEARCH_FTRANSFERTS_LIST",
    DELETE_FTRANSFERT="DELETE_FTRANSFERT",
    PACTH_FTRANSFERTS_UPDATE_STATUS="PACTH_FTRANSFERTS_UPDATE_STATUS",
    GET_FTRANSFERT_GETPHOTO="GET_FTRANSFERT_GETPHOTO",
    GET_FTRANSFERT_DETAIL="GET_FTRANSFERT_DETAIL",
    

    
}

