
export enum  DepartmentsActionType{
    GET_DEPARTMENT_LIST="GET_DEPARTMENT_LIST",
    GET_DEPARTMENTS_CREATE="GET_DEPARTMENTS_CREATE",
    PACTH_DEPARTMENTS_UPDATE="PACTH_DEPARTMENTS_UPDATE",
    GET_SEARCH_DEPARTMENTS_LIST="GET_SEARCH_DEPARTMENTS_LIST",
    DELETE_DEPARTMENT="DELETE_DEPARTMENT"

    
}

