export const SETINTERVALREFRESHDATAVALUE=3000;
export const HOMEPAGESETINTERVALREFRESHDATAVALUE=3000;

export const SETREFRESPROFILE:number =3000; //30 s

export enum FILETRANSFERTTYPER{
      FDT="FDT",
      FDP="FDP"
}