
export enum  RcncontrolsActionType{
    GET_RCNCONTROL_LIST="GET_RCNCONTROL_LIST",
    GET_RCNCONTROLS_CREATE="GET_RCNCONTROLS_CREATE",
    PACTH_RCNCONTROLS_UPDATE="PACTH_RCNCONTROLS_UPDATE",
    GET_SEARCH_RCNCONTROLS_LIST="GET_SEARCH_RCNCONTROLS_LIST",
    DELETE_RCNCONTROL="DELETE_RCNCONTROL",
    PACTH_RCNCONTROLS_UPDATE_STATUS="PACTH_RCNCONTROLS_UPDATE_STATUS",
    GET_RCNCONTROL_GETPHOTO="GET_RCNCONTROL_GETPHOTO",
    GET_RCNCONTROL_LISTV2="GET_RCNCONTROL_LISTV2",
}

