
export enum  DriversActionType{
    GET_DRIVER_LIST="GET_DRIVER_LIST",
    GET_DRIVERS_CREATE="GET_DRIVERS_CREATE",
    PACTH_DRIVERS_UPDATE="PACTH_DRIVERS_UPDATE",
    GET_SEARCH_DRIVERS_LIST="GET_SEARCH_DRIVERS_LIST",
    DELETE_DRIVER="DELETE_DRIVER",
    PACTH_DRIVERS_UPDATE_STATUS="PACTH_DRIVERS_UPDATE_STATUS",
    GET_DRIVERS_GETSTATS="GET_DRIVERS_GETSTATS",

}

