
export enum  AuthUserActionType{
    LOGIN="LOGIN",
    USER_PROFILE="GET_USERS_PROFILE",
    USER_UPDATE_MY_PROFILE="USER_UPDATE_MY_PROFILE",
    USER_CHANGE_MYPASSWORD="USER_CHANGE_MYPASSWORD",

    
}

