
export enum  SuppliersActionType{
    GET_SUPPLIER_LIST="GET_SUPPLIER_LIST",
    GET_SUPPLIERS_CREATE="GET_SUPPLIERS_CREATE",
    PACTH_SUPPLIERS_UPDATE="PACTH_SUPPLIERS_UPDATE",
    GET_SEARCH_SUPPLIERS_LIST="GET_SEARCH_SUPPLIERS_LIST",
    DELETE_SUPPLIER="DELETE_SUPPLIER",
    PACTH_SUPPLIERS_UPDATE_STATUS="PACTH_SUPPLIERS_UPDATE_STATUS",
    GET_SUPPLIERS_GETSTATS="GET_SUPPLIERS_GETSTATS",
    GET_ALL_SUPMANAGER_BY_SUPPLIER_ID="GET_ALL_SUPMANAGER_BY_SUPPLIER_ID",
    
}

