
export enum  UsersActionType{
    GET_USERS_LIST="GET_USERS_LIST",
    GET_SEARCH_USERS_LIST="GET_SEARCH_USERS_LIST",
    GET_USERS_CREATE="GET_USERS_CREATE",
    PACTH_USERS_UPDATE="PACTH_USERS_UPDATE",
    PACTH_RESET_USER_PASSWORD="PACTH_RESET_USER_PASSWORD",
    PACTH_USER_SETTINGS="PACTH_USER_SETTINGS",
    DELETE_USER="DELETE_USER",


    
}

