
export enum  TrailersActionType{
    GET_TRAILER_LIST="GET_TRAILER_LIST",
    GET_TRAILERS_CREATE="GET_TRAILERS_CREATE",
    PACTH_TRAILERS_UPDATE="PACTH_TRAILERS_UPDATE",
    GET_SEARCH_TRAILERS_LIST="GET_SEARCH_TRAILERS_LIST",
    DELETE_TRAILER="DELETE_TRAILER",
    PACTH_TRAILERS_UPDATE_STATUS="PACTH_TRAILERS_UPDATE_STATUS",
    GET_TRAILERS_GETSTATS="GET_TRAILERS_GETSTATS",


   
}

