
export enum  PlacesActionType{
    GET_PLACE_LIST="GET_PLACE_LIST",
    GET_PLACES_CREATE="GET_PLACES_CREATE",
    PACTH_PLACES_UPDATE="PACTH_PLACES_UPDATE",
    GET_SEARCH_PLACES_LIST="GET_SEARCH_PLACES_LIST",
    DELETE_PLACE="DELETE_PLACE"

    
}

