
export enum  OperatorsActionType{
    GET_OPERATORS_LIST="GET_OPERATORS_LIST",
    GET_SEARCH_OPERATORS_LIST="GET_SEARCH_OPERATORS_LIST",
    GET_OPERATORS_CREATE="GET_OPERATORS_CREATE",
    PACTH_OPERATORS_UPDATE="PACTH_OPERATORS_UPDATE",
    DELETE_OPERATOR="DELETE_OPERATOR",
    PACTH_OPERATORS_UPDATE_STATUS="PACTH_OPERATORS_UPDATE_STATUS",


    
}

