
export enum  VehiclesActionType{
    GET_VEHICLE_LIST="GET_VEHICLE_LIST",
    GET_VEHICLES_CREATE="GET_VEHICLES_CREATE",
    PACTH_VEHICLES_UPDATE="PACTH_VEHICLES_UPDATE",
    GET_SEARCH_VEHICLES_LIST="GET_SEARCH_VEHICLES_LIST",
    DELETE_VEHICLE="DELETE_VEHICLE",
    PACTH_VEHICLES_UPDATE_STATUS="PACTH_VEHICLES_UPDATE_STATUS",
    GET_VEHICLES_GETSTATS="GET_VEHICLES_GETSTATS",


   
}

