
export enum  CarriersActionType{
    GET_CARRIER_LIST="GET_CARRIER_LIST",
    GET_CARRIERS_CREATE="GET_CARRIERS_CREATE",
    PACTH_CARRIERS_UPDATE="PACTH_CARRIERS_UPDATE",
    GET_SEARCH_CARRIERS_LIST="GET_SEARCH_CARRIERS_LIST",
    DELETE_CARRIER="DELETE_CARRIER",
    PACTH_CARRIERS_UPDATE_STATUS="PACTH_CARRIERS_UPDATE_STATUS",
    GET_CARRIERS_GETSTATS="GET_CARRIERS_GETSTATS",

}

