
export enum  RolesActionType{
    GET_ROLE_LIST="GET_ROLE_LIST",
    GET_ROLES_CREATE="GET_ROLES_CREATE",
    PACTH_ROLES_UPDATE="PACTH_ROLES_UPDATE",
    GET_SEARCH_ROLES_LIST="GET_SEARCH_ROLES_LIST",
    DELETE_ROLE="DELETE_ROLE"

    
}

