
export enum  RegionsActionType{
    GET_REGION_LIST="GET_REGION_LIST",
    GET_REGIONS_CREATE="GET_REGIONS_CREATE",
    PACTH_REGIONS_UPDATE="PACTH_REGIONS_UPDATE",
    GET_SEARCH_REGIONS_LIST="GET_SEARCH_REGIONS_LIST",
    DELETE_REGION="DELETE_REGION"

    
}

