
export enum  YieldinspectionsActionType{
    GET_YIELDINSPECTION_LIST="GET_YIELDINSPECTION_LIST",
    GET_YIELDINSPECTIONS_CREATE="GET_YIELDINSPECTIONS_CREATE",
    PACTH_YIELDINSPECTIONS_UPDATE="PACTH_YIELDINSPECTIONS_UPDATE",
    GET_SEARCH_YIELDINSPECTIONS_LIST="GET_SEARCH_YIELDINSPECTIONS_LIST",
    DELETE_YIELDINSPECTION="DELETE_YIELDINSPECTION",
    PACTH_YIELDINSPECTIONS_UPDATE_STATUS="PACTH_YIELDINSPECTIONS_UPDATE_STATUS",
    GET_YIELDINSPECTION_GETPHOTO="GET_YIELDINSPECTION_GETPHOTO",
    GET_YIELDINSPECTION_LISTV2="GET_YIELDINSPECTION_LISTV2",
}

