
export enum  ProcurementsActionType{
    GET_PROCUREMENT_LIST="GET_PROCUREMENT_LIST",
    GET_PROCUREMENT_LISTV2="GET_PROCUREMENT_LISTV2",
    GET_PROCUREMENT_DETAIL="GET_PROCUREMENT_DETAIL",
    GET_PROCUREMENTS_CREATE="GET_PROCUREMENTS_CREATE",
    PACTH_PROCUREMENTS_UPDATE="PACTH_PROCUREMENTS_UPDATE",
    PACTH_CONFIRM_PROCUREMENTS_UPDATE="PACTH_CONFIRM_PROCUREMENTS_UPDATE",
    GET_SEARCH_PROCUREMENTS_LIST="GET_SEARCH_PROCUREMENTS_LIST",
    GET_SUMMERY_PROCUREMENTS_LIST="GET_SUMMERY_PROCUREMENTS_LIST",
    DELETE_PROCUREMENT="DELETE_PROCUREMENT",
    PACTH_PROCUREMENTS_UPDATE_STATUS="PACTH_PROCUREMENTS_UPDATE_STATUS",
    GET_PROCUREMENT_GETPHOTO="GET_PROCUREMENT_GETPHOTO",

    GET_EXPORT_TO_EXCEL_PROCUREMENTS_LIST="GET_EXPORT_TO_EXCEL_PROCUREMENTS_LIST",

    //////////STATISTICS SECTION ////////////
    GET_PROCUREMENT_GETSTATS="GET_PROCUREMENT_GETSTATS",
    GET_PROCUREMENT_TOTAL_RECNETWT="GET_PROCUREMENT_TOTAL_RECNETWT",
    GET_PROCUREMENT_AVG_TOTAL_OUTTURN="GET_PROCUREMENT_AVG_TOTAL_OUTTURN",
    GET_PROCUREMENT_GETLAST7ALLSTATS="GET_PROCUREMENT_GETLAST7ALLSTATS",
    GET_PROCUREMENT_GETLAST6MONTHSTATS="GET_PROCUREMENT_GETLAST6MONTHSTATS",


    
}

